---
functional:
  - сайт должен предоставить вомзожность зарегистрироваться 
  - пользователь должен иметь возможность опробовать игру без регистрации 
  - пользователь может создать игру или присоединиться к уже созданной 
  - пользователь должен иметь возможность пригласить соперника по ссылке 
  - возможность авторизации пользователя через GitHub 
  - пользователь должен иметь возможность выбора уровня сложности 
  - пользователь должен иметь возможность выбора кода для игры 
  - должна быть предоставлена возможность выхода из игры или сброса кода 
  - задание должно быть доступно как на русском, так и на английском языках 
  - возможность участия пользователей в турнире, организована турнирная сетка и таблица лидеров 
  - пользователю предоставляется возможность просмотра истории пройденных игр(баттлов) 
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - участник не может влиять на игру соперника (переписывать код)
  - зрители не могут влиять на игру участников 
  - задание должно быть понятным и не содержать логических ошибок, из-за которых невозможно выполнить его правильно 
